import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import ApolloSetting from "../commons/settings/apollo-setting";
import Layout from "../commons/layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const 글로벌폰트 = localFont({
  src: "./fonts/SUIT-Variable.woff2",
  variable: "--글로벌폰트",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ko">
      <body className={`${글로벌폰트.variable}`}>
        <ApolloSetting>
          <Layout>{children}</Layout>
        </ApolloSetting>
      </body>
    </html>
  );
}
