# 1. 운영체제 및 프로그램 설치
FROM ubuntu:22.04

RUN sudo apt install nodejs
RUN sudo npm install -g yarn

# 2. git 클론해서 소스코드 가짜컴퓨터 안에서 다운로드 받기
RUN git clone 내프로젝트주소

# 3. 최종 실행하기
RUN yarn install
RUN yarn build
CMD yarn start